---
title: "Trajectory comparisons"
author: "Daniel Keitley"
date: "12/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(scrabbitr)

```



# Load data
```{r}

r_traj <- loadWOTData("../data-test/rabbit/trajectory_analysis/trajectory/")
m_traj <- loadWOTData("../data-test/mouse/trajectory_analysis/trajectory/")

```


# Compute pseudocells
```{r}
num_points <- 200
win_size <- 0.1

traj.interp <- interWeights2(expDataBatch = counts(traj),
                             trajCond = traj.scorpius$time,
                             numPts = num_points, winSz = win_size)
```


# Compute psuedocell correlation
```{r}

```


# Compute null model
```{r}
source_python("G:/My Drive/Postgrad/PhD/Projects/rabbit-gastrulation-atlas/trajectory_analysis/tests/simulations/prosstt.py")

sim <- simulateDensities(data.frame(x=rabbit.density$x,y=rabbit.density$y),
                         data.frame(x=mouse.density$x,y=mouse.density$y),
                         ncellsA=as.integer(ncol(rabbit.traj)),
                         ncellsB=as.integer(ncol(mouse.traj)))


```

